export const USER_ACTION = 'USER_ACTION';
export const REQUEST_API = 'RESQUEST_API';
export const RESPONSE_API = 'RESPONSE_API';
export const RESPONSE_BUT = 'RESPONSE_BUT';
export const UPDATE_EXPENSES = 'UPDATE_EXPENSES';
